# Generated by Django 5.1.1 on 2025-03-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tinySteps", "0004_alter_externalarticle_model_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectionError_Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("error_type", models.CharField(max_length=100)),
                ("path", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("client_ip", models.GenericIPAddressField(null=True)),
                ("user", models.CharField(blank=True, max_length=150)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("traceback", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Connection Error",
                "verbose_name_plural": "Connection Errors",
                "ordering": ["-timestamp"],
            },
        ),
    ]
